Estilizar interfaz de usuario
NoobSammy/terremotos pull request #1
Opened 2024-09-05 19:17 UTC by JSamuelAP

Se usa la librería **picnic** para aplicar estilos.
Los resultados ahora muestran la hora del terremoto.

2024-09-05 19:34 UTC, NoobSammy commented
Corregir observaciones

2024-09-07 18:08 UTC, NoobSammy requested changes
Corregir observaciones

2024-09-07 18:08 UTC, NoobSammy commented on index.html
> +			<button id="btnBuscar" class="">Buscar</button>
Eliminar atributos `class` vacíos

2024-09-07 18:27 UTC, JSamuelAP commented on index.html
> +			<button id="btnBuscar" class="">Buscar</button>
Listooo

2024-09-07 18:29 UTC, NoobSammy approved these changes
Gracias por atender las correcciones

2024-09-07 18:31 UTC, merged